services:
  - type: web
    name: brain-tumor-mri-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    branch: main
